### ISSUE TITLE
Fastify 5 support

### ISSUE THREAD

**Issue by felixmosh** [turkerdev/fastify-type-provider-zod#104]
Fastify 5 has been released, I've tried this lib with it, but looks like it breaks all the types.

Can you add support for Fastify v5?

**Comment by anniehastur450** [comment]
I believe you can fix it by adding this definition in one of your entry points:

```typescript
declare module 'fastify-type-provider-zod' {
  interface ZodTypeProvider {
    validator: this['schema'] extends ZodType ? z.infer<this['schema']> : unknown;
    serializer: this['schema'] extends ZodType ? z.infer<this['schema']> : unknown;
  }
}
```

But for what I am using I use the [other package](https://www.npmjs.com/package/fastify-zod-openapi) which have the same API as this one and does have Fastify 5 support.

**Comment by Bram-dc** [comment]
https://github.com/turkerdev/fastify-type-provider-zod/pull/97
https://github.com/turkerdev/fastify-type-provider-zod/pull/103
https://www.npmjs.com/package/@bram-dc/fastify-type-provider-zod
 :)

**Comment by rslucena** [comment]
any version released? I'm still having problems with dependency

```
npm warn Could not resolve dependency:
npm warn peer fastify@"^4.0.0" from fastify-type-provider-zod@2.1.0
npm warn node_modules/fastify-type-provider-zod
npm warn   fastify-type-provider-zod@"^2.1.0" from the root project
```

**Comment by Bram-dc** [comment]
I think version 3.0.0 is about to be released from this original repo. My fork will no longer be necessary.

**Comment by kibertoad** [comment]
@felixmosh please try 3.0.0 and let us know how it goes!
