### ISSUE TITLE
Optional fields treated as required in Swagger

### ISSUE THREAD

**Issue by eliyamelamed1** [turkerdev/fastify-type-provider-zod#131]
When using `fastify-type-provider-zod` with Swagger (`fastify-swagger`), optional fields in Zod schemas are incorrectly marked as **required** in the Swagger documentation.  

---

### Steps to Reproduce:  
1. Create a Zod schema with an optional field:  
   ```ts
   const schema = z.object({
     name: z.string(),
     age: z.number().optional(), // Optional field
   });
   ```

2. Use the schema in a Fastify route with Swagger integration.  
3. Check the Swagger docs – `age` is marked as **required**.

---

### Expected Behavior:  
Optional fields in Zod schemas should appear as optional in Swagger.

---

### Actual Behavior:  
Optional fields appear as **required** in the Swagger documentation.

This may be related to the `jsonSchemaTransform` step not handling Zod optional fields correctly.

Let me know if you need further details!

**Comment by eliyamelamed1** [comment]
My bad i was using an old version

**Comment by moh1434** [comment]
i use `"fastify-type-provider-zod": "^4.0.2"` and i have the same issue.
