### ISSUE TITLE
Asynchronous refinements not working

### ISSUE THREAD

**Issue by erwinstone** [turkerdev/fastify-type-provider-zod#22]
Schema:
```typescript
export const loginBody = z.object({
  username: user.shape.username.min(2).refine(async (val) => {
    // verify that username exists in database
    return true
  }),
  password: user.shape.password.min(4),
})
```

Response:
```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Unexpected token A in JSON at position 0"
}
```

**Comment by turkerdev** [comment]
We do parse the schema as sync. Therefore, you cannot use async schema.

> Async should not be used as part of the first validation strategy. This option is used to access Databases and reading them during the validation process may lead to Denial of Service Attacks to your application. If you need to run async tasks, use [Fastify's hooks](https://www.fastify.io/docs/latest/Reference/Hooks) instead after validation completes, such as preHandler.<br>
[Fastify Docs](https://www.fastify.io/docs/latest/Reference/Validation-and-Serialization/#validator-compiler)
