### ISSUE TITLE
Response validation failing with 'safeParse' is not a function 

### ISSUE THREAD

**Issue by alxarch** [turkerdev/fastify-type-provider-zod#3]
Seems to require `jsonShorthand: false` option on the server to work as expected.
Somehow [getSchemaAnyway](https://github.com/fastify/fastify/blob/cdc1114a4da0bb03c39e1e97518673dfd8edc8fa/lib/schemas.js#L113) is called and unless `jsonShorthand` is set to `false` it wraps the schema into
```json
{
  "type": "object",
  "properties": [ZodSchema]
}
```
instead of the expected bare schema

**Comment by turkerdev** [comment]
Can you create a reproduction, please?
https://stackblitz.com

**Comment by alxarch** [comment]
https://stackblitz.com/edit/json-server-cyu7wd?file=index.js

**Comment by shmarts** [comment]
Having the same problem

**Comment by kibertoad** [comment]
Fix PR is up
