### ISSUE TITLE
Additional maintainers

### ISSUE THREAD

**Issue by kibertoad** [turkerdev/fastify-type-provider-zod#4]
Hi! We are considering to use this library at Lokalise, but we are concerned that it's not very actively maintained. Would you be open to accepting a couple of our engineers as co-maintainers to help support the library?

**Comment by turkerdev** [comment]
Sure, sounds good to me.

**Comment by kibertoad** [comment]
Could you please add myself and @rupert-mckay in that case?

**Comment by turkerdev** [comment]
Sent the invite.
