### ISSUE TITLE
How to set params to be form-data

### ISSUE THREAD

**Issue by hugorplobo** [turkerdev/fastify-type-provider-zod#48]
Hi, I'm trying to use a zod object as a form-data params in my route:

![image](https://user-images.githubusercontent.com/53958114/236727539-f5f04ce0-5b8c-4ce8-b3d9-eb1428a3b2f4.png)

But the swagger ui doesn't send the fields. Do I need to specify how the fields need to be sent? How can I do that?

**Comment by pkrinesh** [comment]
Hi @hugorplobo

Yes, you need to add the params in the URL. i.e., `"/register/:param"` at the top.
