### ISSUE TITLE
[Question] Add passthrough() for parser

### ISSUE THREAD

**Issue by HannesOberreiter** [turkerdev/fastify-type-provider-zod#55]
Hi,

thanks for the great library. On some routes I would love to allow additional properties. Is there a way to modify the current compiler with a flag to do `schema.passthrough().parse();`?

https://github.com/colinhacks/zod#passthrough

Thanks in advance!

**Comment by kibertoad** [comment]
Can't that be done on schema level already?

**Comment by HannesOberreiter** [comment]
Could not find how. :( The behaviour of `strict` (if it should fail etc) you can modify at schema level, but not the `passthrough`.

**Comment by kibertoad** [comment]
If you define your body schema as `const myschema = z.object({ // definition }).passthrough()`, that doesn't suffice?

**Comment by HannesOberreiter** [comment]
I not even tried to add passthrough on the object, as the documentation on zod shows the parser in the example and I blacked out. But it makes sense as it is a pipe on the object itself ... 

Sorry about that, thanks for the help!

**Comment by kibertoad** [comment]
np!
