### ISSUE TITLE
fastify-swagger support

### ISSUE THREAD

**Issue by kibertoad** [turkerdev/fastify-type-provider-zod#6]
Using fastify-type-provider-zod together with https://github.com/fastify/fastify-swagger results in route documentation being generated without request schemas.

Configuration used:

```
  app.register(fastifySwagger, {
    exposeRoute: true,
    openapi: {
      info: {
        title: 'SampleApi',
        description: 'Sample backend service',
        version: '1.0.0',
      },
      servers: [
        {
          url: `http://${
            appConfig.bindAddress === '0.0.0.0' ? 'localhost' : appConfig.bindAddress
          }:${appConfig.port}`,
        },
      ],
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
          },
        },
      },
    },
  })

...

export const LOGIN_SCHEMA = z.object({
  username: z.string().max(32).describe('someDescription'),
  password: z.string().max(32),
})

const route =       {
        method: 'POST',
        url: '/login',
        handler: someController,
        schema: { body: LOGIN_SCHEMA, describe: 'test route' },
      },
```

**Comment by kibertoad** [comment]
See https://github.com/fastify/help/issues/728#issuecomment-1205741881
I'm happy to work on support for this, but would need some pointers.
@turkerdev

**Comment by Gomah** [comment]
Hey @kibertoad, @turkerdev, thank you for creating and maintaining this project!

You could potentially use the same approach as `fastify-zod` & leverage [`zod-to-json-schema`](https://github.com/StefanTerdell/zod-to-json-schema) to generate an `openApi3` schema ?

**Comment by kibertoad** [comment]
@Gomah Sounds like a plan! any suggestions where to plug that in?

**Comment by turkerdev** [comment]
@kibertoad I did manage to create a working [demo (CodeSandbox)](https://codesandbox.io/s/distracted-monad-v2lr6x), do not forget to run "dev" script.

**Comment by kibertoad** [comment]
@turkerdev Thank you, will check it out! Do you think this should be included as a part of fastify-type-provider-zod, e. g. as zodFastifySwaggerTransformer? Or you see this as an absolutely separate thing?

**Comment by turkerdev** [comment]
I think we can include it in this package.

**Comment by kibertoad** [comment]
@turkerdev Awesome, I'll create a PR with test then.
Can you take a look at https://github.com/turkerdev/fastify-type-provider-zod/pull/5 prior to that?
