### ISSUE TITLE
The response is typed and accepts unknown keys

### ISSUE THREAD

**Issue by kevbook** [turkerdev/fastify-type-provider-zod#63]
I tried with `strict()` and without `strict()`. Anyone can help?

```js
  fastify.withTypeProvider<ZodTypeProvider>().post(
    '/person',
    {
      schema: {
        body: z.object({ a: z.string() }),
        response: { '2xx': z.object({ b: z.string() }).strict() },
      },
    },
    function (request, reply) {
      console.log(request.body.a); // Typed
      return { b: '9', c: 1 }; // Typed but accepts c
    }
  );
```

**Comment by turkerdev** [comment]
``res.send()``/``reply.send()`` method works fine. i recommend using it.

![image](https://github.com/turkerdev/fastify-type-provider-zod/assets/48413508/5d90948b-2ad4-4b31-aec1-94cab08444a0)

**Comment by kevbook** [comment]
Thank you sir!

**Comment by thelinuxlich** [comment]
Same problem still 
![image](https://github.com/turkerdev/fastify-type-provider-zod/assets/5043/65a46627-8fdc-4055-808b-2b71d3de5e6e)

**Comment by arudenkoofficial** [comment]
If you are looking for some solution – I described my experience here: https://github.com/turkerdev/fastify-type-provider-zod/issues/157#issuecomment-3380691068
