### ISSUE TITLE
NPM Module not up to date with github repo

### ISSUE THREAD

**Issue by BenjaminLindberg** [turkerdev/fastify-type-provider-zod#75]
The NPM Module is outdated and lacks features as `FastifyPluginAsyncZod`.

**Comment by sap471** [comment]
![image](https://github.com/turkerdev/fastify-type-provider-zod/assets/16040140/f8cbf48d-76ec-443c-96be-24c6eae75dec)

![image](https://github.com/turkerdev/fastify-type-provider-zod/assets/16040140/514af9c3-1c3e-4d1a-b63c-7f976dd329ca)

have same problem with this, `FastifyPluginAsyncZod` and `FastifyPluginCallbackZod` is missing

**Comment by BenjaminLindberg** [comment]
@sap471 

I temporarily fixed this problem, i forked this repo and released it as [@benjaminlindberg/fastify-type-provider-zod](https://www.npmjs.com/package/@benjaminlindberg/fastify-type-provider-zod).
But hopefully the official package will get updated soon.

**Comment by mbirkegaard** [comment]
@BenjaminLindberg Thanks for the workaround, handy to have!

**Comment by kibertoad** [comment]
1.2.0 is out now. Sorry for the delay
