### ISSUE TITLE
Module has no exported member 'FastifyPluginAsyncZod'

### ISSUE THREAD

**Issue by theanh098** [turkerdev/fastify-type-provider-zod#83]
![image](https://github.com/turkerdev/fastify-type-provider-zod/assets/95953163/3ed1e27d-fa8c-45a4-8934-80d48b8d07f5)
I got this error when try to import this type. I am using version ^1.1.9

**Comment by edosrecki** [comment]
Problem is that the maintainer hasn't published the new release yet. :( In the meantime you can use the forked package: https://github.com/turkerdev/fastify-type-provider-zod/issues/75

**Comment by edosrecki** [comment]
@turkerdev can we please get a release with this?

**Comment by kibertoad** [comment]
Sorry for the delay. 1.2.0 is out now, please let me know if it works now!

**Comment by theanh098** [comment]
@kibertoad it worked, thanks.
