### ISSUE TITLE
What's the new preferred way of accessing `ResponseValidationError`?

### ISSUE THREAD

**Issue by erunion** [turkerdev/fastify-type-provider-zod#94]
With the 2.0.0 release `ResponseValidationError` is no longer exported from the main export, instead only from `dist/ResponseValidationError`:

```js
import { ResponseValidationError } from 'fastify-type-provider-zod/dist/ResponseValidationError';
```

Is loading it from here the new preferred way of accessing this error class or can/should it be added back into the main export?

**Comment by kibertoad** [comment]
This is a bug. I'll restore it, thanks!

**Comment by erunion** [comment]
Brilliant, thank you!

**Comment by MunifTanjim** [comment]
Any updates on this?
